name: Build and Deploy to Web

on:
  push:
    branches: [ main ]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout repository
      - uses: subosito/flutter-action@v2.4.0
        name: Set up Flutter
      - name: Set up Pages
        uses: actions/configure-pages@v1
      - name: Switch Flutter channel
        run: flutter channel master
      - name: Make sure Flutter is up to date
        run: flutter upgrade
      - name: Enable Web support
        run: flutter config --enable-web
      - name: Install system dependencies
        run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev util-linux liblzma-dev libgcrypt-dev -y
      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade
      - name: Build Pangolin for Web
        run: flutter build web --release
      - name: Add CNAME
        run: echo "web.dahliaos.io" >> build/web/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/web/'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
